services:
  postgres_ask:
    restart: always
    image: postgres:latest
    container_name: postgres_ask
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ask
    volumes:
      - postgres_ask:/data/postgres
  adminer_ask:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  postgres_ask:
